// Mock data for pinLayer

const PEOPLE = [
  { id: 'ren',  name: 'Ren Kawamura',   handle: 'ren',  hue: 268, role: 'Designer' },
  { id: 'mara', name: 'Mara Eklund',    handle: 'mara', hue: 14,  role: 'QA Engineer' },
  { id: 'idris',name: 'Idris Okafor',   handle: 'idris',hue: 158, role: 'PM' },
  { id: 'nina', name: 'Nina Petrova',   handle: 'nina', hue: 198, role: 'Engineer' },
  { id: 'sam',  name: 'Sam Holloway',   handle: 'sam',  hue: 38,  role: 'Engineer' },
  { id: 'tova', name: 'Tova Lindgren',  handle: 'tova', hue: 320, role: 'Support' },
];

const ISSUE_TYPES = [
  { id: 'visual',  label: 'Visual bug',     short: 'visual' },
  { id: 'layout',  label: 'Layout issue',   short: 'layout' },
  { id: 'copy',    label: 'Copy issue',     short: 'copy' },
  { id: 'broken',  label: 'Broken behavior',short: 'broken' },
  { id: 'a11y',    label: 'Accessibility',  short: 'a11y' },
  { id: 'perf',    label: 'Performance',    short: 'perf' },
];

const SEVERITIES = ['critical', 'high', 'medium', 'low'];

// Sessions — grouped annotation issues
const SESSIONS = [
  {
    id: 'PL-0142',
    title: 'Checkout review — payment step regressions',
    url: 'app.northwind.io/checkout/payment',
    favicon: 'NW',
    faviconHue: 268,
    counts: { critical: 2, high: 5, medium: 5, low: 2 },
    pins: 14,
    reporter: 'ren',
    integration: { name: 'Linear', synced: 14, status: 'ok' },
    status: 'open',
    ago: '2h ago',
    updated: '2026-05-24T09:42:00Z',
  },
  {
    id: 'PL-0141',
    title: 'Marketing homepage hero — typography pass',
    url: 'northwind.io',
    favicon: 'NW',
    faviconHue: 268,
    counts: { critical: 0, high: 1, medium: 4, low: 3 },
    pins: 8,
    reporter: 'idris',
    integration: { name: 'Jira', synced: 8, status: 'ok' },
    status: 'in-progress',
    ago: '5h ago',
    updated: '2026-05-24T06:10:00Z',
  },
  {
    id: 'PL-0140',
    title: 'Dashboard empty states + onboarding nudges',
    url: 'app.northwind.io/dashboard',
    favicon: 'NW',
    faviconHue: 268,
    counts: { critical: 0, high: 2, medium: 6, low: 4 },
    pins: 12,
    reporter: 'mara',
    integration: { name: 'Linear', synced: 12, status: 'ok' },
    status: 'in-progress',
    ago: '11h ago',
    updated: '2026-05-24T01:01:00Z',
  },
  {
    id: 'PL-0139',
    title: 'Settings — danger zone wording & gating',
    url: 'app.northwind.io/settings/security',
    favicon: 'NW',
    faviconHue: 268,
    counts: { critical: 1, high: 0, medium: 2, low: 0 },
    pins: 3,
    reporter: 'tova',
    integration: { name: 'GitHub', synced: 3, status: 'ok' },
    status: 'open',
    ago: '1d ago',
    updated: '2026-05-23T14:22:00Z',
  },
  {
    id: 'PL-0138',
    title: 'Mobile nav — overflow, hit-targets, focus order',
    url: 'app.northwind.io (mobile)',
    favicon: 'NW',
    faviconHue: 268,
    counts: { critical: 0, high: 3, medium: 5, low: 1 },
    pins: 9,
    reporter: 'nina',
    integration: { name: 'Jira', synced: 9, status: 'pending' },
    status: 'open',
    ago: '1d ago',
    updated: '2026-05-23T10:30:00Z',
  },
  {
    id: 'PL-0137',
    title: 'Pricing page — plan card alignment + footnotes',
    url: 'northwind.io/pricing',
    favicon: 'NW',
    faviconHue: 268,
    counts: { critical: 0, high: 0, medium: 3, low: 4 },
    pins: 7,
    reporter: 'ren',
    integration: { name: 'Linear', synced: 6, status: 'pending' },
    status: 'open',
    ago: '2d ago',
    updated: '2026-05-22T16:40:00Z',
  },
  {
    id: 'PL-0136',
    title: 'Auth — magic-link error states are unclear',
    url: 'app.northwind.io/login',
    favicon: 'NW',
    faviconHue: 268,
    counts: { critical: 0, high: 2, medium: 1, low: 1 },
    pins: 4,
    reporter: 'sam',
    integration: { name: 'Linear', synced: 4, status: 'failed' },
    status: 'resolved',
    ago: '3d ago',
    updated: '2026-05-21T08:11:00Z',
  },
  {
    id: 'PL-0135',
    title: 'Reports — date picker contrast + keyboard nav',
    url: 'app.northwind.io/reports',
    favicon: 'NW',
    faviconHue: 268,
    counts: { critical: 0, high: 1, medium: 2, low: 3 },
    pins: 6,
    reporter: 'mara',
    integration: { name: 'GitHub', synced: 6, status: 'ok' },
    status: 'resolved',
    ago: '4d ago',
    updated: '2026-05-20T13:33:00Z',
  },
  {
    id: 'PL-0134',
    title: 'Billing — invoice download silently fails',
    url: 'app.northwind.io/billing',
    favicon: 'NW',
    faviconHue: 268,
    counts: { critical: 1, high: 1, medium: 0, low: 0 },
    pins: 2,
    reporter: 'tova',
    integration: { name: 'Jira', synced: 2, status: 'ok' },
    status: 'in-progress',
    ago: '4d ago',
    updated: '2026-05-20T09:00:00Z',
  },
];

// Pins for the detail page — first session
const PINS = [
  { i: 1, severity: 'critical', type: 'broken', status: 'open',
    title: 'Apple Pay button silently fails on first tap',
    body: "Steps: 1) Click \"Pay with Apple Pay\". 2) Sheet doesn't render — promise resolves without error. Reproducible in Safari 18.3 on macOS. Second tap works. Likely event-handler attach order; we listen before the sheet boots.",
    assignee: 'nina', anchor: 'button.btn-apple-pay[data-step="payment"]', stale: false,
    activity: [
      { t: '2h ago', who: 'ren',  text: 'Pinned and submitted to Linear' },
      { t: '1h ago', who: 'nina', text: 'Assigned to me — repro in dev now' },
      { t: '12m ago',who: 'nina', text: 'Status → In progress' },
    ]
  },
  { i: 2, severity: 'critical', type: 'broken', status: 'in-progress',
    title: '"Place order" button stays enabled with invalid CVV',
    body: 'Submission still goes through and gateway rejects later. We should validate locally and disable + announce.',
    assignee: 'sam', anchor: 'form#payment button[type="submit"]', stale: false,
  },
  { i: 3, severity: 'high', type: 'visual', status: 'open',
    title: 'Card logos misaligned against input baseline',
    body: 'Visa / Mastercard / Amex icons sit 2px high. Compare to Figma 274:Checkout / Payment / v4.',
    assignee: 'ren', anchor: '.payment-icons > svg', stale: false,
  },
  { i: 4, severity: 'high', type: 'a11y', status: 'open',
    title: 'CVV tooltip is keyboard-inaccessible',
    body: 'Trigger is a div, opens on hover only. Needs button + focus + esc-to-close.',
    assignee: 'idris', anchor: '.cvv-help-trigger', stale: false,
  },
  { i: 5, severity: 'high', type: 'layout', status: 'open',
    title: 'Coupon row collapses awkwardly under 480px',
    body: 'Input gets squeezed, "Apply" wraps to two lines. Either stack vertically or shrink padding.',
    assignee: 'ren', anchor: '.coupon-row', stale: true,
  },
  { i: 6, severity: 'high', type: 'visual', status: 'open',
    title: 'Order summary divider draws over total row',
    body: '1px hairline. z-index on the sticky footer is winning. Lower the divider, or raise the row.',
    assignee: 'nina', anchor: '.summary hr.total-divider', stale: false,
  },
  { i: 7, severity: 'high', type: 'copy', status: 'open',
    title: '"Confirm and pay" — wording inconsistent with cart',
    body: 'Cart uses "Place order". Pick one across the funnel.',
    assignee: 'idris', anchor: 'button.confirm-pay', stale: false,
  },
  { i: 8, severity: 'medium', type: 'visual', status: 'open',
    title: 'Input focus ring is barely visible on dark surface',
    body: 'Contrast 2.1:1. Bump to accent at higher alpha.',
    assignee: 'ren', anchor: 'input.field', stale: false,
  },
  { i: 9, severity: 'medium', type: 'copy', status: 'open',
    title: 'Tax-included disclosure is buried',
    body: 'Move under the total, not in the FAQ accordion.',
    assignee: 'idris', anchor: '.faq-accordion', stale: false,
  },
  { i: 10, severity: 'medium', type: 'layout', status: 'open',
    title: 'Sticky footer overlaps the last form row at 900px wide',
    body: 'Add bottom-padding equal to footer height on .form-wrap.',
    assignee: 'sam', anchor: '.form-wrap', stale: false,
  },
  { i: 11, severity: 'medium', type: 'a11y', status: 'open',
    title: 'Error messages are color-only — needs icon + role="alert"',
    body: 'Failing WCAG 1.4.1. Pair red text with an inline alert icon and a live region.',
    assignee: 'idris', anchor: '.field-error', stale: false,
  },
  { i: 12, severity: 'medium', type: 'visual', status: 'open',
    title: 'Country selector caret is the wrong icon',
    body: "It's a triangle; rest of the UI uses chevrons.",
    assignee: 'ren', anchor: 'select.country .caret', stale: false,
  },
  { i: 13, severity: 'low', type: 'visual', status: 'open',
    title: 'Trailing comma in shipping address preview',
    body: 'Render is `123 Hawthorne Ave,,  Portland, OR`',
    assignee: 'sam', anchor: '.address-preview', stale: false,
  },
  { i: 14, severity: 'low', type: 'copy', status: 'open',
    title: 'Footer link "Refund Policy" should be sentence-case',
    body: 'Match the rest of the footer.',
    assignee: 'idris', anchor: 'footer a.refund', stale: false,
  },
];

const INTEGRATIONS = [
  { id: 'linear',    name: 'Linear',          cat: 'Issue Tracker', connected: true,  account: 'northwind / Design',  hue: 252, glyph: 'L', desc: 'Create Linear issues from every pin. Map severity to priority and route by project.' },
  { id: 'jira',      name: 'Jira',            cat: 'Issue Tracker', connected: true,  account: 'NW-WEB',              hue: 215, glyph: 'J', desc: 'Two-way sync with Jira projects. Mirror status and reflect comments back to pins.' },
  { id: 'github',    name: 'GitHub Issues',   cat: 'Issue Tracker', connected: true,  account: 'northwind/app',       hue: 0,   glyph: 'G', desc: 'Open GitHub issues with labels, milestones, and the failing element selector attached.' },
  { id: 'gitlab',    name: 'GitLab',          cat: 'Issue Tracker', connected: false, hue: 24,  glyph: 'GL',desc: 'File issues against GitLab projects with rich anchor metadata.' },
  { id: 'azure',     name: 'Azure DevOps',    cat: 'Issue Tracker', connected: false, hue: 200, glyph: 'AZ',desc: 'Push pins as Work Items into your Azure Boards backlog.' },
  { id: 'shortcut',  name: 'Shortcut',        cat: 'Issue Tracker', connected: false, hue: 28,  glyph: 'S', desc: 'Create stories and epics directly from grouped sessions.' },

  { id: 'slack',     name: 'Slack',           cat: 'Messaging',     connected: true,  account: '#design-review',      hue: 290, glyph: 'SL',desc: 'Get a thread per session with rich previews and quick triage actions.' },
  { id: 'teams',     name: 'Microsoft Teams', cat: 'Messaging',     connected: false, hue: 235, glyph: 'T', desc: 'Route session notifications to Teams channels by repo or label.' },
  { id: 'discord',   name: 'Discord',         cat: 'Messaging',     connected: false, hue: 235, glyph: 'D', desc: 'Lightweight channel pings when a critical pin lands.' },

  { id: 'figma',     name: 'Figma',           cat: 'Design',        connected: true,  account: 'Northwind / Web',     hue: 332, glyph: 'F', desc: 'Cross-link pins with Figma frames. Compare implementation against design.' },
  { id: 'storybook', name: 'Storybook',       cat: 'Design',        connected: false, hue: 332, glyph: 'SB',desc: 'Anchor pins to component stories, not just pages.' },

  { id: 'notion',    name: 'Notion',          cat: 'Documentation', connected: false, hue: 0,   glyph: 'N', desc: 'Append weekly digests to a docs page automatically.' },
  { id: 'confluence',name: 'Confluence',      cat: 'Documentation', connected: false, hue: 215, glyph: 'C', desc: 'Publish triage reports into spaces by team.' },

  { id: 'webhook',   name: 'Custom webhook',  cat: 'Developer',     connected: false, hue: 268, glyph: '{}', desc: 'Receive every event as JSON. Pipe it anywhere you want.' },
];

window._DATA = { PEOPLE, ISSUE_TYPES, SEVERITIES, SESSIONS, PINS, INTEGRATIONS };
